#@TYPE: Machine
#@NAME: bananapi-f3
#@SOC: SpacemiT K1
#@DESCRIPTION: Machine configuration for Banana PI F3

require conf/machine/include/k1.inc

KERNEL_DEVICETREE ?= "spacemit/k1-bananapi-f3.dtb"

UBOOT_MACHINE = "bananapi-f3_defconfig"
