#@TYPE: Machine
#@NAME: beaglev-ahead
#@SOC: Xuantie C910
#@DESCRIPTION: Machine configuration for the Beagle-V Ahead board

require include/c910.inc

# Extend the list from riscv-common.inc
MACHINE_FEATURES += "usb wifi bluetooth"

#============================================
# SBI Configuration
unset RISCV_SBI_PAYLOAD
#============================================

#============================================
# Kernel Configuration
KERNEL_DEVICETREE ?= "thead/th1520-beaglev-ahead.dtb"
KERNEL_IMAGETYPE = "Image"
# Install kernel modules by default
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append = " kernel-modules"

#============================================

#============================================
# Uboot Configuration
UBOOT_MACHINE = "th1520_beaglev_ahead_defconfig"
UBOOT_ENV = ""
#============================================

#============================================
# Firmware Configuration
TH1520_TRAINING_FW_SRC = "lpddr4x-3733-singlerank.lua"
#============================================

#============================================
# Image Configuration
IMAGE_BOOT_FILES = " \
    ${KERNEL_IMAGETYPE} \
    th1520-beaglev-ahead.dtb \
    extlinux_sd.conf;extlinux/extlinux.conf \
"
WKS_FILE ?= "beaglev-ahead.wks"
#============================================

#============================================
# Common Preferred Providers
PREFERRED_PROVIDER_virtual/kernel ?= "linux-mainline"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"
EXTRA_IMAGEDEPENDS += "u-boot firmware-th1520"
#============================================
WKS_FILE_DEPENDS:append = " gptfdisk-native"
