#@TYPE: Machine
#@NAME: beaglev-fire
#@SOC: Microchip PolarFire SoC
#@DESCRIPTION: Machine configuration for the BeagleBoard BeagleV-Fire

require conf/machine/include/riscv-common.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-mainline"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"

RISCV_SBI_FDT = "mpfs-beaglev-fire.dtb"

KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE = "microchip/${RISCV_SBI_FDT}"

UBOOT_MACHINE = "beaglev_fire_defconfig"
UBOOT_ENV_SUFFIX = "scr"

WKS_FILE_DEPENDS:append = " u-boot"

IMAGE_BOOT_FILES = " \
    ${KERNEL_IMAGETYPE} \
    ${RISCV_SBI_FDT} \
    boot.scr \
"

WKS_FILE = "beaglev-fire.wks"
