#@TYPE: Machine
#@NAME: beaglev-ahead
#@SOC: T-Head 1520
#@DESCRIPTION: Machine configuration for the Beagle-V Ahead board

require include/th1520.inc

# Extend the list from riscv-common.inc
MACHINE_FEATURES += "usb wifi bluetooth"

#============================================
# Kernel Configuration
KERNEL_DEVICETREE ?= "thead/th1520-beaglev-ahead.dtb"
#============================================

#============================================
# Uboot Configuration
UBOOT_MACHINE = "th1520_beaglev_ahead_defconfig"
UBOOT_ENV = ""
#============================================

#============================================
# Firmware Configuration
TH1520_TRAINING_FW_SRC = "lpddr4x-3733-singlerank.lua"
#============================================

#============================================
# Image Configuration
IMAGE_BOOT_FILES = " \
    ${KERNEL_IMAGETYPE} \
    th1520-beaglev-ahead.dtb \
    extlinux.conf;extlinux/extlinux.conf \
"
#============================================
