#@TYPE: Machine
#@NAME: dc-roma-fml13v01
#@SOC: StarFive JH7110
#@DESCRIPTION: Machine configuration for the DeepComputing DC-ROMA RISC-V Mainboard (FML13V01)

require include/jh7110-common.inc

PREFERRED_PROVIDER_virtual/kernel:dc-roma-fml13v01 = "linux-mainline"
PREFERRED_PROVIDER_virtual/bootloader:dc-roma-fml13v01 = "u-boot-starfive"

# I don't think the visionfive2 vendor PVR (PowerVR) drivers work with
# mainline, so drop them.
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:remove = " \
    linux-firmware-visionfive2-imggpu \
    vdec-module \
    venc-module \
    jpu-module \
    visionfive2-pvr-graphics-tools \
"

# Intel Wi-Fi 6E AX210 (M.2 module)
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "linux-firmware-iwlwifi-misc"

RISCV_SBI_FDT ?= "jh7110-deepcomputing-fml13v01.dtb"

KERNEL_DEVICETREE ?= "starfive/jh7110-deepcomputing-fml13v01.dtb"
KERNEL_IMAGETYPE = "Image"

UBOOT_MACHINE = "starfive_visionfive2_defconfig"
UBOOT_DTB_BINARY = "starfive_visionfive2.dtb"
UBOOT_ENV = ""
UBOOT_LOADADDRESS = "0x40200000"

KERNEL_CLASSES:append = " kernel-fit-extra-artifacts"
EXTRA_IMAGEDEPENDS += "linux-yocto-fitimage"

WKS_FILE = "dc-roma-fml13v01.wks"
IMAGE_BOOT_FILES = " \
    fitImage;starfiveu.fit \
    vf2_uEnv.txt \
"
