#@TYPE: Machine
#@NAME: K3 Pico-ITX
#@SOC: Spacemit K3
#@DESCRIPTION: Machine configuration for K3 Pico-ITX development board

require conf/machine/include/k3-vendor.inc

KERNEL_DEVICETREE ?= "spacemit/k3-pico-itx.dtb"

IMAGE_BOOT_FILES += " \
        k3-pico-itx.dtb \
	"

MACHINE_EXTRA_RRECOMMENDS += "\
        linux-firmware-rtl8851 \
        linux-firmware-rtl8852 \
        linux-firmware-rtl8922 \
        "
