#@TYPE: Machine
#@NAME: milkv-duo
#@SOC: CVITEK CV1800B
#@DESCRIPTION: Machine configuration for Milk-V Duo

require conf/machine/include/milkv-common.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-milkv-duo-dev"
PREFERRED_VERSION_openocd-native = "riscv"
PREFERRED_VERSION_openocd = "riscv"
UBOOT_MACHINE ?= "milkv-duo_defconfig"

WKS_FILE ?= "milkv-duo.wks"
