#@TYPE: Machine
#@NAME: milkv-duo
#@SOC: CVITEK CV1800B
#@DESCRIPTION: Machine configuration for Milk-V Duo 64Mb board

require conf/machine/include/milkv-duo.inc
require conf/machine/include/milkv-duo-upstream-uboot.inc

UBOOT_MACHINE ?= "milkv_duo_defconfig"

KERNEL_DEVICETREE ?= "sophgo/cv1800b-milkv-duo.dtb"
