#@TYPE: Machine
#@NAME: milkv-duo
#@SOC: CVITEK CV1800B
#@DESCRIPTION: Machine configuration for Milk-V Duo 64Mb board

require conf/machine/include/milkv-duo.inc

UBOOT_MACHINE ?= "milkv_duo_defconfig"

IMAGE_BOOT_FILES ?= "fip.bin uImage.fit"
