#@TYPE: Machine
#@NAME: milkv-duos
#@SOC: SOPHGO SG2000
#@DESCRIPTION: Machine configuration for Milk-V Duo S

require conf/machine/include/milkv-duo.inc

# No upstream U-Boot support for SG2000: keep the vendor U-Boot fork and the
# vendor FSBL (see milkv-duo-fsbl.bb).
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-milkv-duo"
UBOOT_MACHINE ?= "milkv-duo_defconfig"

IMAGE_BOOT_FILES ?= " \
                    default.dtb \
                    fip.bin \
                    uEnv.txt \
                    uImage.fit \
                    "
