#@TYPE: Machine
#@NAME: orangepi-r2s
#@SOC: Ky X1
#@DESCRIPTION: Machine configuration for OrangePi R2S

require include/k1-vendor.inc

KERNEL_DEVICETREE ?= "ky/x1_orangepi-r2s.dtb"

IMAGE_BOOT_FILES += " \
	x1_orangepi-r2s.dtb"

WKS_FILE ?= "orangepi-r2s-usb.wks"

MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
