#@TYPE: Machine
#@NAME: orangepi-rv2-mainline
#@SOC: Spacemit K1
#@DESCRIPTION: Machine configuration for OrangePi RV2 with mainline Linux

require conf/machine/include/k1.inc

KERNEL_DEVICETREE ?= "spacemit/k1-orangepi-rv2.dtb"

# OrangePi RV2 not supported yet in mainline U-Boot. A similar machine works.
UBOOT_MACHINE = "bananapi-f3_defconfig"
