#@TYPE: Machine
#@NAME: visionfive2-mainline
#@SOC: StarFive JH7110
#@DESCRIPTION: Machine configuration for the VisionFive 2 board with mainline Linux and U-Boot

require include/visionfive2-common.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-mainline-jh7110"
