SUMMARY = "GNU awk pattern-matching language"
DESCRIPTION = "GNU awk is a pattern-matching language. It is useful for \
manipulating text files. It is often used as a data extraction and reporting \
tool. This version in particular is based on the description in \
The AWK Programming Language, by Al Aho, Brian Kernighan, and Peter Weinberger."

HOMEPAGE = "https://www.gnu.org/software/gawk/"
SECTION = "console/utils"
LICENSE = "GPL-3.0-or-later"
LIC_FILES_CHKSUM = "file://README;beginline=1;endline=20;md5=3b5b1b1b1b1b1b1b1b1b1b1b1b1b1b1b \
                    file://COPYING;md5=59530bdf33659b29e73d4adb9f9f6552"

SRC_URI = "${GNU_MIRROR}/gawk/gawk-${PV}.tar.xz \
           file://0001-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0002-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0003-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0004-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0005-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0006-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0007-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0008-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0009-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0010-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0011-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0012-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0013-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0014-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0015-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0016-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0017-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0018-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0019-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0020-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0021-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0022-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0023-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0024-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0025-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0026-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0027-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0028-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0029-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0030-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0031-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0032-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0033-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0034-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0035-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0036-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0037-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0038-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0039-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0040-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0041-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0042-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0043-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0044-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0045-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0046-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0047-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0048-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0049-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0050-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0051-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0052-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0053-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0054-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0055-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0056-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0057-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0058-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0059-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0060-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0061-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0062-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0063-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0064-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0065-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0066-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0067-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0068-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0069-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0070-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0071-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0072-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0073-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0074-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0075-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0076-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0077-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0078-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0079-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0080-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0081-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0082-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0083-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0084-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0085-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0086-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0087-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0088-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0089-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0090-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0091-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0092-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0093-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0094-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0095-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0096-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0097-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0098-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0099-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0100-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0101-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0102-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0103-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0104-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0105-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0106-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0107-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0108-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0109-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0110-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0111-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0112-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0113-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0114-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0115-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0116-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0117-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0118-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0119-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0120-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0121-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0122-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0123-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0124-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0125-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0126-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0127-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0128-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0129-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0130-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0131-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0132-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0133-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0134-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0135-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0136-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0137-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0138-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0139-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0140-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0141-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0142-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0143-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0144-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0145-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0146-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0147-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0148-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0149-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0150-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0151-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0152-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0153-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0154-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0155-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0156-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0157-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0158-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0159-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0160-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0161-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0162-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0163-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0164-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0165-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0166-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0167-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0168-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0169-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0170-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0171-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0172-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0173-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0174-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0175-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0176-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0177-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0178-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0179-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0180-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0181-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0182-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0183-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0184-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0185-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0186-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0187-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0188-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0189-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0190-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0191-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0192-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0193-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0194-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0195-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0196-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0197-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0198-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0199-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0200-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0201-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0202-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0203-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0204-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0205-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0206-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0207-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0208-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0209-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0210-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0211-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0212-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0213-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0214-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0215-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0216-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0217-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0218-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0219-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0220-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0221-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0222-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0223-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0224-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0225-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0226-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0227-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0228-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0229-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0230-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0231-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0232-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0233-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0234-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0235-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0236-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0237-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0238-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0239-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0240-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0241-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0242-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0243-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0244-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0245-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0246-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0247-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0248-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0249-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0250-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0251-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0252-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0253-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0254-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0255-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0256-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0257-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0258-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0259-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0260-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0261-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0262-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0263-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0264-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0265-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0266-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0267-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0268-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0269-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0270-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0271-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0272-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0273-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0274-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0275-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0276-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0277-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0278-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0279-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0280-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0281-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0282-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0283-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0284-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0285-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0286-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0287-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0288-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0289-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0290-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0291-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0292-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0293-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0294-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0295-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0296-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0297-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0298-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0299-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0300-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0301-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0302-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0303-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0304-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0305-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0306-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0307-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0308-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0309-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0310-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0311-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0312-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0313-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0314-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0315-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0316-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0317-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0318-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0319-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0320-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0321-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0322-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0323-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0324-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0325-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0326-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0327-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0328-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0329-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0330-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0331-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0332-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0333-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0334-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0335-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0336-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0337-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0338-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0339-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0340-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0341-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0342-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0343-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0344-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0345-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0346-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0347-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0348-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0349-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0350-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0351-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0352-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0353-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0354-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0355-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0356-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0357-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0358-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0359-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0360-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0361-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0362-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0363-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0364-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0365-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0366-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0367-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0368-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0369-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0370-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0371-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0372-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0373-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0374-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0375-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0376-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0377-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0378-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0379-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0380-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0381-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0382-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0383-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0384-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0385-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0386-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0387-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0388-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0389-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0390-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0391-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0392-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0393-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0394-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0395-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0396-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0397-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0398-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0399-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0400-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0401-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0402-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0403-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0404-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0405-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0406-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0407-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0408-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0409-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0410-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0411-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0412-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0413-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0414-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0415-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0416-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0417-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0418-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0419-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0420-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0421-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0422-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0423-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0424-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0425-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0426-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0427-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0428-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0429-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0430-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0431-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0432-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0433-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0434-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0435-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0436-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0437-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0438-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0439-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0440-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0441-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0442-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0443-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0444-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0445-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0446-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0447-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0448-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0449-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0450-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0451-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0452-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0453-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0454-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0455-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0456-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0457-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0458-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0459-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0460-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0461-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0462-Use-AC_SYS_LARGEFILE-to-enable-large-file-support.patch \
           file://0463-Use
