header:
  version: 14

local_conf_header:
  default: |
    # -- Default local.conf from meta-poky/conf/local.conf.sample -- #
    EXTRA_IMAGE_FEATURES ?= "\
        allow-empty-password \
        empty-root-password \
        allow-root-login \
        post-install-logging"
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"
    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
    PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
    PACKAGE_CLASSES = "package_rpm"
    SDKMACHINE = "x86_64"
    CONF_VERSION = "2"

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""
